### ISSUE TITLE
Windows install issue

### ISSUE THREAD

**Issue by davidmezzetti** [neuml/paperai#2]
It was reported that paperai can't be installed in a Windows environment due to the following error:

**ValueError: path 'src/python/' cannot end with '/'**

**Comment by davidmezzetti** [comment]
Note: This project has dependencies that require compiling native code. Linux enviroments usually work without an issue. For Windows, see https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by davidmezzetti** [comment]
Closing this issue, will reopen if the changes didn't fix the problem.

**Comment by DavidRivasPhD** [comment]
I installed the (visualstudio) C++ compiler noted above, which allowed me to install almost everything, including fastText and faiss. However, I was unable to install Torch https://pypi.org/project/torch/  because it seems that it is not supported by Windows. So I tried  Linux and was able to install paperai successfully.

**Comment by davidmezzetti** [comment]
Thank you for the follow up on this. 

Looking at the pytorch.org website, it looks like you should be able to install PyTorch in Windows via pip:

``
pip install torch===1.6.0 torchvision===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
``

**Comment by DavidRivasPhD** [comment]
Thank you for your prompt replies.  I'm only working in Linux now.
